// This file is generated by mindcanary-protocol. Do not edit by hand.

export const PROTOCOL_VERSION = 1 as const;

export const DEFAULT_DAILY_RHYTHM_INSIGHT_LIMIT = 20 as const;
export const MAX_DAILY_RHYTHM_INSIGHT_LIMIT = 100 as const;

export const DEFAULT_DAILY_TIMELINE_LIMIT = 30 as const;
export const MAX_DAILY_TIMELINE_LIMIT = 366 as const;

export const MIN_CHECK_IN_SCALE = 1 as const;
export const MAX_CHECK_IN_SCALE = 7 as const;
export const MAX_SLEEP_MINUTES = 1440 as const;
export const MAX_CONTEXT_TAGS = 8 as const;

export const MAX_ANNOTATION_TEXT_BYTES = 1000 as const;

export const SIGNAL_IDS = [
  "browser.tab_switch_count",
  "browser.open_tab_count_min",
  "browser.open_tab_count_max",
  "browser.open_tab_count_mean",
  "browser.tab_open_count",
  "browser.tab_close_count",
  "browser.window_count_max",
  "browser.active_seconds",
  "browser.idle_seconds",
  "browser.retained_across_day_count",
  "browser.continuous_scrolling_seconds",
  "os.active_seconds",
  "os.idle_seconds",
  "os.lock_count",
  "os.unlock_count",
  "os.suspend_count",
  "os.resume_count",
] as const;

export type SignalId = (typeof SIGNAL_IDS)[number];

export const BROWSER_STARTER_SIGNAL_IDS = [
  "browser.tab_switch_count",
  "browser.open_tab_count_max",
  "browser.open_tab_count_mean",
  "browser.window_count_max",
  "browser.active_seconds",
  "browser.idle_seconds",
  "browser.retained_across_day_count",
] as const satisfies readonly SignalId[];

export const CONTEXT_TAGS = [
  "deadline",
  "travel",
  "illness",
  "news_cycle",
  "job_uncertainty",
  "social_conflict",
  "exercise",
  "medication_change",
  "substance_use",
  "unusual_good_event",
  "other",
] as const;

export type ContextTag = (typeof CONTEXT_TAGS)[number];

export interface ObservationPeriod {
  start: string;
  end: string;
  time_zone: string;
}

export interface Metric {
  signal: SignalId;
  value: number;
}

export interface AggregateBatch {
  batch_id: string;
  source_instance_id: string;
  sequence: number;
  period: ObservationPeriod;
  metrics: Metric[];
}

export interface CheckInRecord {
  check_in_id: string;
  occurred_at: string;
  time_zone: string;
  local_date: string;
  sleep_minutes?: number | null;
  perceived_sleep_need?: number | null;
  mood?: number | null;
  energy?: number | null;
  irritability?: number | null;
  concentration?: number | null;
  impulsivity?: number | null;
  medication_taken?: boolean | null;
  substance_use?: boolean | null;
  context_tags: ContextTag[];
}

export interface AnnotationRecord {
  annotation_id: string;
  created_at: string;
  time_zone: string;
  local_date: string;
  start_minute?: number | null;
  end_minute?: number | null;
  text: string;
  context_tags: ContextTag[];
}

export interface DailyRhythmSummary {
  daily_snapshot_count: number;
  browser_day_count: number;
  os_day_count: number;
  check_in_day_count: number;
  insight_count_before_limit: number;
  insights_truncated: boolean;
}

export type RhythmInsightDimension =
  | "browser_tabs"
  | "tab_switching"
  | "active_time"
  | "computer_active_time"
  | "sleep"
  | "energy";

export type RhythmChangeDirection = "higher" | "lower";

export interface RhythmEvidence {
  label: string;
  value: string;
}

export interface RhythmInsight {
  local_date: string;
  dimension: RhythmInsightDimension;
  direction: RhythmChangeDirection;
  summary: string;
  evidence: RhythmEvidence[];
}

export interface RhythmDimensionReadiness {
  dimension: RhythmInsightDimension;
  status: RhythmReadinessStatus;
  comparable_day_count: number;
  minimum_day_count: number;
}

export type RhythmReadinessStatus =
  | "change_described"
  | "within_baseline"
  | "needs_sustained_change"
  | "missing_current"
  | "insufficient_baseline"
  | "zero_baseline"
  | "unstable_baseline";

export interface DailyTimelineSummary {
  calendar_day_count_before_limit: number;
  returned_day_count: number;
  browser_day_count: number;
  os_day_count: number;
  check_in_day_count: number;
  annotation_day_count: number;
  missing_day_count: number;
  days_truncated: boolean;
}

export interface DailyBrowserTimeline {
  open_tab_count_mean?: number | null;
  open_tab_count_max?: number | null;
  tab_switch_count?: number | null;
  retained_across_day_count?: number | null;
  continuous_scrolling_seconds?: number | null;
  active_seconds?: number | null;
  idle_seconds?: number | null;
  recorded_bucket_count: number;
}

export interface DailyOsTimeline {
  active_seconds?: number | null;
  idle_seconds?: number | null;
  lock_count?: number | null;
  unlock_count?: number | null;
  suspend_count?: number | null;
  resume_count?: number | null;
  recorded_bucket_count: number;
}

export interface DailyCheckInTimeline {
  sleep_minutes?: number | null;
  mood?: number | null;
  energy?: number | null;
  irritability?: number | null;
  concentration?: number | null;
  impulsivity?: number | null;
  check_in_count: number;
  context_tags: ContextTag[];
}

export interface DailyTimelineDay {
  local_date: string;
  browser?: DailyBrowserTimeline | null;
  os?: DailyOsTimeline | null;
  check_in?: DailyCheckInTimeline | null;
  annotations: AnnotationRecord[];
}

export interface LocalDataSummary {
  aggregate_batch_count: number;
  aggregate_metric_count: number;
  check_in_count: number;
  context_tag_count: number;
  annotation_count: number;
  annotation_context_tag_count: number;
}

export interface SignalCollectionSetting {
  signal: SignalId;
  enabled: boolean;
  changed_at?: string | null;
}

export interface SignalRecordSummary {
  metric_record_count: number;
  affected_batch_count: number;
}

export interface LocalDataExport {
  export_directory: string;
  report_path: string;
  daily_browser_csv_path: string;
  daily_os_csv_path: string;
  daily_check_in_csv_path: string;
  annotations_csv_path: string;
  summary: LocalDataSummary;
}

export interface LocalBackup {
  backup_path: string;
  created_at: string;
  format_version: number;
  schema_version: number;
  recovery_secret: string;
  summary: LocalDataSummary;
}

export interface LocalBackupMetadata {
  backup_path: string;
  created_at: string;
  format_version: number;
  schema_version: number;
}

export type OperatingSystem = "linux" | "macos" | "windows" | "other";

export type DesktopEnvironment = "gnome" | "kde" | "other" | "unknown";

export type SessionType = "x11" | "wayland" | "other" | "unknown";

export type PlatformCapabilityId =
  | "os_lock_and_session_events"
  | "os_active_idle_duration"
  | "foreground_application_category";

export type PlatformCapabilityStatus = "available" | "planned" | "unavailable";

export interface PlatformCapability {
  capability: PlatformCapabilityId;
  status: PlatformCapabilityStatus;
  detail: string;
}

export interface PlatformCapabilities {
  operating_system: OperatingSystem;
  desktop_environment: DesktopEnvironment;
  session_type: SessionType;
  capabilities: PlatformCapability[];
}

export type ProtocolRequest =
  | { type: "health"; protocol_version: typeof PROTOCOL_VERSION }
  | { type: "get_source_status"; protocol_version: typeof PROTOCOL_VERSION }
  | {
      type: "ingest_aggregate";
      protocol_version: typeof PROTOCOL_VERSION;
      batch: AggregateBatch;
    }
  | {
      type: "submit_check_in";
      protocol_version: typeof PROTOCOL_VERSION;
      check_in: CheckInRecord;
    }
  | {
      type: "save_annotation";
      protocol_version: typeof PROTOCOL_VERSION;
      annotation: AnnotationRecord;
    }
  | {
      type: "prepare_delete_annotation";
      protocol_version: typeof PROTOCOL_VERSION;
      annotation_id: string;
    }
  | {
      type: "delete_annotation";
      protocol_version: typeof PROTOCOL_VERSION;
      annotation_id: string;
      confirmation_token: string;
    }
  | {
      type: "get_daily_rhythm_insights";
      protocol_version: typeof PROTOCOL_VERSION;
      limit?: number | null;
    }
  | {
      type: "get_daily_timeline";
      protocol_version: typeof PROTOCOL_VERSION;
      limit?: number | null;
    }
  | {
      type: "get_collection_settings";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "get_platform_capabilities";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "set_signal_collection";
      protocol_version: typeof PROTOCOL_VERSION;
      signal: SignalId;
      enabled: boolean;
    }
  | {
      type: "prepare_delete_signal_records";
      protocol_version: typeof PROTOCOL_VERSION;
      signal: SignalId;
    }
  | {
      type: "delete_signal_records";
      protocol_version: typeof PROTOCOL_VERSION;
      signal: SignalId;
      confirmation_token: string;
    }
  | {
      type: "get_local_data_summary";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "prepare_export_local_records";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "export_local_records";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      export_directory: string;
    }
  | {
      type: "prepare_create_local_backup";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "create_local_backup";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      backup_path: string;
    }
  | {
      type: "verify_local_backup";
      protocol_version: typeof PROTOCOL_VERSION;
      backup_path: string;
      recovery_secret: string;
    }
  | {
      type: "restore_local_backup";
      protocol_version: typeof PROTOCOL_VERSION;
      backup_path: string;
      recovery_secret: string;
    }
  | {
      type: "prepare_clear_local_records";
      protocol_version: typeof PROTOCOL_VERSION;
    }
  | {
      type: "clear_local_records";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
    };

export type ServiceStatus = "ready" | "degraded";
export type SourceType = "browser" | "os" | "check_in";
export type SourceHealth =
  | "never_seen"
  | "active"
  | "stale"
  | "disabled"
  | "unavailable";

export interface SourceStatus {
  source: SourceType;
  health: SourceHealth;
  last_received_at?: string | null;
}

export type IngestDisposition =
  | "stored"
  | "stored_filtered"
  | "duplicate"
  | "discarded_disabled";
export type ErrorCode =
  | "invalid_frame"
  | "invalid_request"
  | "message_too_large"
  | "sequence_conflict"
  | "unsupported_protocol_version"
  | "invalid_confirmation"
  | "internal";

export type ProtocolResponse =
  | {
      type: "health";
      protocol_version: typeof PROTOCOL_VERSION;
      service_version: string;
      status: ServiceStatus;
    }
  | {
      type: "source_status";
      protocol_version: typeof PROTOCOL_VERSION;
      generated_at: string;
      sources: SourceStatus[];
    }
  | {
      type: "ingest_acknowledged";
      protocol_version: typeof PROTOCOL_VERSION;
      batch_id: string;
      disposition: IngestDisposition;
    }
  | {
      type: "check_in_acknowledged";
      protocol_version: typeof PROTOCOL_VERSION;
      check_in_id: string;
      disposition: IngestDisposition;
    }
  | {
      type: "annotation_saved";
      protocol_version: typeof PROTOCOL_VERSION;
      annotation_id: string;
    }
  | {
      type: "delete_annotation_confirmation";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      expires_at: string;
      annotation_id: string;
    }
  | {
      type: "annotation_deleted";
      protocol_version: typeof PROTOCOL_VERSION;
      annotation_id: string;
    }
  | {
      type: "daily_rhythm_insights";
      protocol_version: typeof PROTOCOL_VERSION;
      generated_at: string;
      summary: DailyRhythmSummary;
      readiness: RhythmDimensionReadiness[];
      insights: RhythmInsight[];
    }
  | {
      type: "daily_timeline";
      protocol_version: typeof PROTOCOL_VERSION;
      generated_at: string;
      summary: DailyTimelineSummary;
      days: DailyTimelineDay[];
    }
  | {
      type: "collection_settings";
      protocol_version: typeof PROTOCOL_VERSION;
      settings: SignalCollectionSetting[];
    }
  | {
      type: "platform_capabilities";
      protocol_version: typeof PROTOCOL_VERSION;
      capabilities: PlatformCapabilities;
    }
  | {
      type: "delete_signal_records_confirmation";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      expires_at: string;
      signal: SignalId;
      summary: SignalRecordSummary;
    }
  | {
      type: "signal_records_deleted";
      protocol_version: typeof PROTOCOL_VERSION;
      signal: SignalId;
      deleted: SignalRecordSummary;
    }
  | {
      type: "local_data_summary";
      protocol_version: typeof PROTOCOL_VERSION;
      summary: LocalDataSummary;
    }
  | {
      type: "export_local_records_confirmation";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      expires_at: string;
      summary: LocalDataSummary;
    }
  | {
      type: "local_records_exported";
      protocol_version: typeof PROTOCOL_VERSION;
      export: LocalDataExport;
    }
  | {
      type: "create_local_backup_confirmation";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      expires_at: string;
      summary: LocalDataSummary;
    }
  | {
      type: "local_backup_created";
      protocol_version: typeof PROTOCOL_VERSION;
      backup: LocalBackup;
    }
  | {
      type: "local_backup_verified";
      protocol_version: typeof PROTOCOL_VERSION;
      backup: LocalBackupMetadata;
    }
  | {
      type: "local_backup_restored";
      protocol_version: typeof PROTOCOL_VERSION;
      backup: LocalBackupMetadata;
      restored: LocalDataSummary;
    }
  | {
      type: "clear_local_records_confirmation";
      protocol_version: typeof PROTOCOL_VERSION;
      confirmation_token: string;
      expires_at: string;
      summary: LocalDataSummary;
    }
  | {
      type: "local_records_cleared";
      protocol_version: typeof PROTOCOL_VERSION;
      deleted: LocalDataSummary;
    }
  | {
      type: "error";
      protocol_version: typeof PROTOCOL_VERSION;
      code: ErrorCode;
    };
